export const PATH = {
  REGISTRATION: "/registration",
  LOGIN: "/login",
  ERROR: "/404",
  EDIT_PROFILE: "/edit",
  PROFILE: "/",
  MAIN: "/main",
  // EDIT_PACK: '/main/pack-list/edit-pack',
  TEST: "/test",
  CHANGE_PASSWORD: "/change-pass/:token",
  PASSWORD_RECOVERY: "/pass-recovery",
  CARDS: "/main/cards",
  CARD_ID: "/main/cards/:id",
  // CARDS: '/main/packs/:id',
  PACKS: "/main/packs",
  WAITING: "/",
  LEARN: "/main/packs/learn",
  LEARN_PACK: "/main/packs/learn/:id",
};
